In [1]:
import numpy as np

The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, ensuring that they have compatible shapes for these operations.

In [2]:
v = np.array([1, 2, 3])   
w = np.array([4, 5])

In [5]:
# Outer product of vectors v and w
print(v.reshape((3,1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]]) 
x

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
v

array([1, 2, 3])

In [7]:
# Broadcasting vector v to matrix x 
print(x + v) 
  

[[2 4 6]
 [5 7 9]]


In [11]:
# Broadcasting vector w to the transposed matrix x 
print((x.T + w).T) 

[[ 5  6  7]
 [ 9 10 11]]


In [12]:
# Reshaping vector w and broadcasting to matrix x 
print(x + np.reshape(w, (2, 1))) 
  


[[ 5  6  7]
 [ 9 10 11]]


In [13]:
# Broadcasting scalar multiplication to matrix x 
print(x * 2) 

[[ 2  4  6]
 [ 8 10 12]]


# Estimation of Variable | set 1

Variability: It is the import dimension that measures the data variation i.e. whether the data is spread out or tightly clustered. Also known as Dispersion When working on data sets in Machine Learning or Data Science, involves many steps – variance measurement, reduction, and distinguishing random variability from the real one. identifying sources of real variability, making decisions regarding the pre-processing choice or model selection based on it.

Terms related to Variability Metrics : 

-> Deviation 
-> Variance
-> Standard Deviation
-> Mean Absolute Deviation
-> Median Absolute Deviation
-> Order Statistics
-> Range
-> Percentile 
-> Inter-quartile Range

Deviation: We can call it – errors or residuals also. It is the measure of how different/dispersed the values are, from the central/observed value. 

Variance (s2): It is the best-known measure to estimate the variability as it is Squared Deviation. One can call it mean squared error as it is the average of standard deviation.

In [17]:
sequence = [2,3,5,6,7,9]
var =np.var(sequence)
print("The variance is: ", var)

The variance is:  5.5555555555555545


Sequence : [2, 3, 5, 6, 7, 9] 
Mean              = 5.33
Total Terms, n    = 6
Squared Deviation = (2 - 5.33)2 + (3 - 5.33)2 + (5 - 5.33)2
                    (6 - 5.33)2 + (7 - 5.33)2 + (9 - 5.33)2
Variance          = Squared Deviation / n

In [21]:
Standard Deviation   = (Variance)1/2

SyntaxError: invalid syntax (1699086611.py, line 1)

Standard Deviation: It is the square root of Variance. Is also referred to as Euclidean Norm.

In [18]:
np.std(sequence)
#np.sqrt(var)

2.357022603955158

Mean Absolute Deviation: One can estimate a typical estimation for these deviations. If we average the values, the negative deviations would offset the positive ones. Also, the sum of deviations from the mean is always zero. So, it is a simple approach to take the average deviation itself.

In [23]:
def mad(data):
    return np.mean(np.absolute(data - np.mean(data)))
Sequence = [2, 4, 6, 8] 

print ("Mean Absolute Deviation : ", mad(Sequence))


Mean Absolute Deviation :  2.0


In [24]:
# Initializing the array
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2) 
 
print('First array:') 
print(arr1)
 
print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)
 
print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))
 
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [25]:
# Python code to perform reciprocal operation
# on NumPy array
import numpy as np 
arr = np.array([25, 1.33, 1, 1, 100]) 

print('Our array is:')
print(arr)

print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr))

arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)

print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr2))


Our array is:
[ 25.     1.33   1.     1.   100.  ]

After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]

The second array is:
[25]

After applying reciprocal function:
[0]


numpy.power() This function treats elements in the first input array as the base and returns it raised to the power of the corresponding element in the second input array.

In [ ]:
arr = np.array([5, 10, 15]) 
 
print('First array is:') 
print(arr)
 
print('\nApplying power function:') 
print(np.power(arr, 2))
 
print('\nSecond array is:') 
arr1 = np.array([1, 2, 3]) 
print(arr1)
 
print('\nApplying power function again:') 
print(np.power(arr, arr1))

numpy.mod() This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result. 

In [27]:
arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 

In [28]:
print(np.mod(arr,arr1))

[1 0 2]


In [29]:
print(np.remainder(arr,arr1))

[1 0 2]


In [30]:
# Python program illustrating 
# gcd() method 
import numpy as np 

arr1 = [120, 24, 42, 10] 
arr2 = [2250, 12, 20, 50] 

print ("arr1 : ", arr1) 
print ("arr2 : ", arr2) 

print ("\nGCD of arr1 and arr2 : ", np.gcd(arr1, arr2)) 
print ("\nGCD of arr1 and 10 : ", np.gcd(arr1, 10)) 
		


arr1 :  [120, 24, 42, 10]
arr2 :  [2250, 12, 20, 50]

GCD of arr1 and arr2 :  [30 12  2 10]

GCD of arr1 and 10 :  [10  2  2 10]
