# Array creation using numpy methods 

In [1]:
import numpy as np

numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.



In [9]:
a1 = np.empty(2,dtype=np.int64)
print(a1)

[ 927103479103710267 7421608289154976779]


In [10]:
a2 = np.empty([2,2],dtype= np.int64)
print(a2)

[[            0 2872679297232]
 [2872673854576 2872673616032]]


In [11]:
a3 = np.empty([3,3],dtype= np.int32)
print(a3)

[[        0         1         0]
 [      668      1544         0]
 [      768       668 170816372]]


numpy.zeros(shape, dtype = None, order = ‘C’) : Return a new array of given shape and type, with zeros.

In [14]:
a4 = np.zeros(2,dtype=int)
a4

array([0, 0])

In [15]:
a5 = np.zeros([2,2],dtype = int)
a5

array([[0, 0],
       [0, 0]])

In [17]:
a6 = np.zeros([3,3],dtype = float)
a6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

numpy.reshape(array, shape, order = ‘C’) : Shapes an array without changing data of array.

In [23]:
arr = np.arange(0,8,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
new_array = arr.reshape(2,4)
new_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
new_array1 = arr.reshape(4,2)
new_array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [38]:
new_array2 =np.arange(8).reshape(2,2,2)
new_array2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)

The advantage of numpy.arange() over the normal in-built range() function is that it allows us to generate sequences of numbers that are not integers.

In [43]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.

In [39]:
print(new_array1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [40]:
new_array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
print(new_array)

[[0 1 2 3]
 [4 5 6 7]]


In [42]:
new_array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
arr = np.zeros([2,2],dtype=[('x',float),('y',int)])
arr

array([[(0., 0), (0., 0)],
       [(0., 0), (0., 0)]], dtype=[('x', '<f8'), ('y', '<i4')])

In [50]:
arr = np.zeros(2,dtype=[('x',float),('y',int)])
arr

array([(0., 0), (0., 0)], dtype=[('x', '<f8'), ('y', '<i4')])

In [51]:
arr = np.zeros([2,],dtype=[('x',float),('y',int)])
arr

array([(0., 0), (0., 0)], dtype=[('x', '<f8'), ('y', '<i4')])

In [52]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 

In [56]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) : –The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

In [59]:
np.eye(2,2,dtype=int)

array([[1, 0],
       [0, 1]])

In [60]:
np.eye(3,3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.eye(6,6,dtype=int,k=1)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

In [62]:
np.eye(6,6,dtype=int,k=-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

Random() return the random module provides various methods to create arrays filled with random values.

In [75]:
np.random.random(5)

array([0.45470081, 0.49032942, 0.40108751, 0.65925701, 0.48208986])

Random() return the random module provides various methods to create arrays filled with random values.

In [82]:
np.random.rand(2,3)

array([[0.01580745, 0.80219514, 0.36878483],
       [0.31431643, 0.19892084, 0.53300274]])

The function numpy.random.randn() is used to generate random numbers from a standard normal distribution. This distribution is also known as a Gaussian distribution or a bell curve, and has a mean of 0 and a standard deviation of 1. The random numbers generated by this function are commonly referred to as standard normal or z-scores.

In [79]:
np.random.randn(2,3)

array([[-1.16826891, -1.14606145, -0.44256747],
       [ 0.21553196,  2.43332801,  0.51945909]])

In [80]:
iterable = (i*i for i in range(8))
np.fromiter(iterable,dtype=int)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

# 1-D NumPy Array Functions

numpy.max() This function return the maximum value in an array or along a specified axis.

In [84]:
arr1 = np.arange(0,1000,50)
arr1

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600,
       650, 700, 750, 800, 850, 900, 950])

In [85]:
arr1.max()

950

In [86]:
arr1.min()

0

Argmax() Function
numpy.argmax() index of the maximum value (argmax):To find the index of the maximum value in an array.

In [90]:
np.argmax(arr1)

19

In [91]:
np.min(arr1)

0

Create an Empty Numpy Array
To create an empty NumPy array, we can use the numpy.empty() function. The empty() function in NumPy is used to create an empty array with a specified shape. An empty NumPy array is an array that is initialized with arbitrary values, and its shape is determined by the user. An array in NumPy that is empty has random values as its initial values, and the user specifies how it should be shaped.

Create a Full Numpy Array
To create a full NumPy array, you can use the numpy.full() function. The full() function in NumPy creates an array of a given shape and fills it with a specified value. A full NumPy array is an array where all the elements have the same predefined value. This is useful when you want to initialize an array with a specific value.

In [92]:
np.empty((2,3))

array([[0.01580745, 0.80219514, 0.36878483],
       [0.31431643, 0.19892084, 0.53300274]])

In [93]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

How to create a vector in Python using NumPy

In [96]:
vec1 = np.array([1,2,3,4])
vec1
#horizontal vector

array([1, 2, 3, 4])

In [99]:
vec2 = np.array([[1],[2],[3],[4]])
vec2
#vertical Vector

array([[1],
       [2],
       [3],
       [4]])

In [100]:
np.add(vec1,vec2)

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [101]:
vec1.dot(vec2)

array([30])

In [103]:
#element wise
vec1*vec2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])