In [2]:
import numpy as np

Indexing a NumPy array means accessing the elements of the NumPy array at the given index.

There are two types of indexing in NumPy: basic indexing and advanced indexing.

Slicing a NumPy array means accessing the subset of the array. It means extracting a range of elements from the data.

# Basic Slicing and indexing -Shallow Copy

In [3]:
array = np.arange(1,10).flatten()

In [4]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(array[:])

[1 2 3 4 5 6 7 8 9]


In [9]:
print(array[8])

9


In [13]:
array = np.arange(1,10)

In [14]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(array[2:8:1])

[3 4 5 6 7 8]


# Advanced indexing-Deep Copy

In [16]:
arr = np.arange(1,21).reshape(5,4)

In [20]:
print(arr[[0,1,2,3],[0,1,2,3]])

[ 1  6 11 16]


In [21]:
a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50])

[ 80 100]


# Accessing Data Along Multiple Dimensions Arrays in Python Numpy

In [23]:
#1D
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [26]:
print("The number is",arr[2])

The number is 3


In [28]:
#2D
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(arr[1,0])

4


In [32]:
print(arr[:,2])

[3 6 9]


In [33]:
print(arr[1,:])

[4 5 6]


In [34]:
# 3-dimensional array 
array3D = np.array([[[ 0,  1,  2],
                     [ 3,  4,  5],
                     [ 6,  7,  8]],
  
                    [[ 9, 10, 11],
                     [12, 13, 14],
                     [15, 16, 17]],
 
                    [[18, 19, 20],
                     [21, 22, 23],
                     [24, 25, 26]]])
 

In [35]:
print(array3D[1,1,2])

14


# How to access different rows of a multidimensional 

In [36]:
#2d
array = np.arange(1,21).reshape(4,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
print(array[[0,1]])
#print 

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [40]:
print(array[0,1])

2
