# NumPy – Python Library

NumPy is a short form for Numerical Python

Why Numpy ?
NumPy revolutionized the way we handle numerical data in Python. It is created to address the limitations of traditional Python lists when it comes to numerical computing. It is developed by Travis Olliphant in 2005.

What is NumPy? 
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It is open-source software.

In [3]:
import numpy as np

# Arrays in NumPy

In NumPy, dimensions are called axes. The number of axes is rank.
NumPy&#x2019s array class is called ndarray. It is also known by the alias array.

In [10]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)
print("The numpy array is of type",type(arr))
print("The size of the numpy array:",arr.size)
print("The shape of the numpy array",arr.shape)
print("The dimension: ",arr.ndim)
print("The datatype of elements that this array stores:",arr.dtype)

[[1 2 3]
 [4 5 6]]
The numpy array is of type <class 'numpy.ndarray'>
The size of the numpy array: 6
The shape of the numpy array (2, 3)
The dimension:  2
The datatype of elements that this array stores: int32


1. You can create an array from a regular Python list or tuple using the array() function. The type of the resulting array is deduced from the type of the elements in the sequences. Let’s see this implementation:

In [22]:
#list
arr1 = np.array([[1,2,3],
                 [4,5,6]],dtype='float')
print("Array created using passed list: ",arr1)

arr2 = np.array((1,2,3))
print("Array created using Tuple: ",arr2)

Array created using passed list:  [[1. 2. 3.]
 [4. 5. 6.]]
Array created using Tuple:  [1 2 3]


 Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.

In [33]:
a1 = np.zeros((2,3))
print("Array with all elements as Zeros:\n",a1)

a2 = np.ones((2,3))
print("Array with all elements as ones:\n",a2)

a3 = np.full((3,3),7,dtype='complex')
print("Array with all elements as 7 and of type complex\n",a3)

a4 = np.random.random((2,3))
print("Array with random elements: \n",a4)

Array with all elements as Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array with all elements as ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array with all elements as 7 and of type complex
 [[7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]]
Array with random elements: 
 [[0.88893316 0.64531909 0.5394297 ]
 [0.62861598 0.45683248 0.59664391]]


3. arange: This function returns evenly spaced values within a given interval. Step size is specified.

In [37]:
print("The sequential of values: ",np.arange(0,50,5))
#start,stop,step

The arrange of values:  [ 0  5 10 15 20 25 30 35 40 45]


linspace: It returns evenly spaced values within a given interval.

In [39]:
g = np.linspace(0,10,4)
print("The array of 4 values betwenn 0 to 10",g)


The array of 4 values betwenn 0 to 10 [ 0.          3.33333333  6.66666667 10.        ]


Flatten

In [41]:
b1 = np.array([[1,2,3],[4,5,6]])
print(b1)
print("flattened numpy array",b1.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Operations on a single NumPy array

In [44]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(arr)
arr.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


(6, 3)

In [61]:
a6 = np.array([1,2,3,5])
print("Adding:",a6+1)
print("Subtracting",a6 -1)
print("Multiply:",a6*2)
print("Squarring",a6**2)
a6*=2
print("Doubling is same as multiplying",a6)

print("Array before transpose:\n",arr)
print("Transpose: \n",arr.T)

Adding: [2 3 4 6]
Subtracting [0 1 2 4]
Multiply: [ 2  4  6 10]
Squarring [ 1  4  9 25]
Doubling is same as multiplying [ 2  4  6 10]
Array before transpose:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Transpose: 
 [[ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]
 [ 3  6  9 12 15 18]]


# NumPy – Unary Operators

 This includes sum, min, max, etc
 axis = 1 -> Row wise
 axis = 0 ->column wise

In [55]:
print("The array: \n",arr)

The array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [60]:
print("The largest element:",arr.max())
print("The smallest element :",arr.min())
print("The max element row-wise: ",arr.max(axis=1))
print("The minimum of element column-wise ",arr.min(axis=0))
print("The Sum: ",arr.sum())

The largest element: 18
The smallest element : 1
The max element row-wise:  [ 3  6  9 12 15 18]
The minimum of element column-wise  [1 2 3]
The Sum:  171


# NumPy – Binary Operators

In [66]:
b1 = np.array([[1,2,3],
                [4,5,6],
                 [7,8,9]])
b2 = np.array([[1,2,3],
               [4,5,6],
              [7,8,9]])

print("Additioin :\n",b1+b2)
print("Element wise multiplication:\n ",b1*b2)
print("Matrixmultiplication: \n",b1.dot(b2))

Additioin :
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Element wise multiplication:
  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Matrixmultiplication: 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Introduction to NymPy’s ufuncs
NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc. 

In [71]:
c1 = np.array([0,1/4,1/2,3/4,1])
print("The sine Operations: ",np.sin(c1))
print("The exponential Oprations:",np.exp(c1))
print("The Square root : ",np.sqrt(c1))

The sine Operations:  [0.         0.24740396 0.47942554 0.68163876 0.84147098]
The exponential Oprations: [1.         1.28402542 1.64872127 2.11700002 2.71828183]
The Square root :  [0.         0.5        0.70710678 0.8660254  1.        ]


# NumPy Sorting Arrays

In [84]:
print(arr)
arr = arr.T
a1 = np.array([[1,4,2],
              [6,-7,2],
              [4,1,7]])


[[ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]
 [ 3  6  9 12 15 18]]


In [85]:
# print("The array wise sorting",np.sort(arr,axis=None))
print("Row wise Sorting: ",np.sort(a1,axis=1))
print("Column wise Sorting: ",np.sort(a1,axis=0))

Row wise Sorting:  [[ 1  2  4]
 [-7  2  6]
 [ 1  4  7]]
Column wise Sorting:  [[ 1 -7  2]
 [ 4  1  2]
 [ 6  4  7]]


1. Why NumPy arrays are better than Python lists?
NumPy is not only better in performance but it also provides us with several functionalities like broadcasting, indexing, slicing.
NumPy arrays are memory efficient as it stores the homogenous data in contiguous blocks of memory, where lists can store heterogenous data.
NumPy supports multidimensional arrays which allows easy representation.
2. What are ndarrays in NumPy?
ndarrays or n-dimensional arrays are capable of storing homogenous elements. They have a fixed size which is defined at the time of creation.

# Python Numpy

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

In [86]:
r1 = np.array([1,2,3])
print("Array witj 1 dimension:",r1)
r2 = np.array([[1,2,3],
              [4,5,6]])
print("Array with 2 dimension:",r2)

Array witj 1 dimension: [1 2 3]
Array with 2 dimension: [[1 2 3]
 [4 5 6]]


# Accessing the array Index

In [89]:
print("Intial Array\n",arr)


Intial Array
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [92]:
#printing First 4 rows and alternate columns
print(arr[:4,::2])

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [96]:
print(arr[3,1])
print(arr[4,2])

11
15


In [102]:
# Printing elements at
# specific Indices
index = arr[[0,1,2,3,4],
            [1,2,1,0,2]]
print(index)

[ 2  6  8 10 15]


# Data Types in Numpy

In [107]:
x = np.array([1,2,3])
print("DataType: ",x.dtype)
y = np.array([4.0,5,0,6.0])
print("DataType: ",y.dtype)
z= np.array([1,2,3], dtype = np.int64)
print(z.dtype)

DataType:  int32
DataType:  float64
int64


# Math Operations on DataType array

In [111]:
x1 = np.array([[1,2],
             [3,4]],dtype=np.float64)
x2 =np.array([[5,6],
             [7,8]],dtype = np.float64)

In [112]:
print(np.add(x1,x2))

[[ 6.  8.]
 [10. 12.]]


In [115]:
print(np.sum(x1))

10.0



# NumPy Array in Python

Python lists are a substitute for arrays, but they fail to deliver the performance required while computing large sets of numerical data.

To address this issue we use the NumPy library of Python. NumPy offers an array object called ndarray.

In [117]:
#single dimensional
w = np.array([1,2,3,4,])
print(w)

[1 2 3 4]


In [118]:
#passing list as a numpy array
li = [3,4,56]
a = np.array(li)

print("The type of list: ", type(li))
print("The typye of numpy array", type(a))

The type of list:  <class 'list'>
The typye of numpy array <class 'numpy.ndarray'>


In [120]:
#passing tuple as a numpy array
tu = (3,4,56)
a = np.array(tu)

print("The type of list: ", type(tu))
print("The typye of numpy array", type(a))

The type of list:  <class 'tuple'>
The typye of numpy array <class 'numpy.ndarray'>


# Why is the Numpy Array so Fast?
Numpy arrays are written mostly in C language. Being written in C, the arrays are stored in contiguous memory locations which makes them accessible and easier to manipulate. This means that you can get the performance level of a C code with the ease of writing a Python program.

Homogeneous Data: Arrays store elements of the same data type, making them more compact and memory-efficient than lists.
Fixed Data Type: Arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.
Contiguous Memory: Arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.

Types of Array:
One Dimensional Array
Multi-Dimensional Array

Some different way of creating Numpy Array :

1. numpy.array(): The Numpy array object in Numpy is called ndarray. We can create ndarray using numpy.array() function.

In [121]:
ar =np.array([1,23,45,48])
ar

array([ 1, 23, 45, 48])

# 2. numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [134]:
iterable = (a*a for a in range (8))
new_array = np.fromiter(iterable,float)
new_array

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

3. numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.


In [138]:
print(np.arange(0,1000,100),int)

[  0 100 200 300 400 500 600 700 800 900] <class 'int'>


In [140]:
print(np.arange(0,1000,100,dtype=np.float64))

[  0. 100. 200. 300. 400. 500. 600. 700. 800. 900.]


4. numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 

Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [142]:
np.linspace(0,100,5,dtype=np.int64)

array([  0,  25,  50,  75, 100], dtype=int64)

5. numpy.empty(): This function create a new array of given shape and type, without initializing value.

Syntax: numpy.empty(shape, dtype=float, order=’C’)

In [154]:
np.empty([4,3],dtype=np.int64,order='f')

array([[      2040066929512,        206158430208, 3544387221759222584],
       [                 64, 4135765954635773492, 3919928524323305317],
       [                  0, 3774687620269172276, 3688783657125296184],
       [                  0, 3990580014771221809, 7149805494187931188]],
      dtype=int64)

6. numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).

In [157]:
print(np.ones([3,4],dtype=np.int32))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [159]:
print(np.zeros([4,3],dtype=np.int32))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
