In [4]:
import numpy as np
from numpy import linalg

In [2]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [3]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

# rank, determinant, trace, etc. of an array.

In [5]:
print("Rank of the matrix",np.linalg.matrix_rank(A))

Rank of the matrix 3


In [9]:
print("Determinant of the matrix",int(np.linalg.det(A)))

Determinant of the matrix -306


In [10]:
print("Inverse of the matrix\n",np.linalg.inv(A))

Inverse of the matrix [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [12]:
print("Trace of the matrix\n",np.trace(A))

Inverse of the matrix
 11


In [16]:
print("Raised to power 2 ",np.linalg.matrix_power(A,2))

Squaring this matrix:  [[42 12 18]
 [26 48 29]
 [58 42 91]]


# Matrix eigenvalues Functions

In [17]:
np.linalg.eigh(A)

(array([-7.15957544,  4.56008699, 13.59948845]),
 array([[ 0.192948  , -0.86902847, -0.45558818],
        [-0.86570993,  0.06778288, -0.49593528],
        [ 0.46186296,  0.49009693, -0.739248  ]]))

# the magnitude of a vector in NumPy

In [32]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

In [33]:
np.linalg.norm(vec)

3.7416573867739413

In [34]:
m = np.array([[1, 2, 3], 
              [2, 3, 4], 
              [4, 5, 6]]) 
  
print("Printing the Original square array:\n", 
      m) 
  
# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]


In [35]:
print("Eigen Values: ",w)

Eigen Values:  [ 1.08309519e+01 -8.30951895e-01 -3.58709921e-16]


In [36]:
print("Eigen Vecorts:  ",v)

Eigen Vecorts:   [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]
