In [1]:
import numpy as np

# Matrix manipulation in Python

In [4]:
matrix1 = np.array([[7,3],[4,8]])
matrix2 = np.array([[2,1],[1,4]])
print("Matrix1: \n",matrix1)
print("Matrix2: \n",matrix2)

Matrix1: 
 [[7 3]
 [4 8]]
Matrix2: 
 [[2 1]
 [1 4]]


In [3]:
print("Element Wise Addtion: ",np.add(matrix1,matrix2))

Element Wise Multiplication:  [[ 9  4]
 [ 5 12]]


In [5]:
print("Element Wise subtraction: ",np.subtract(matrix1,matrix2))

Element Wise subtraction:  [[5 2]
 [3 4]]


In [6]:
print("Element Wise subtraction: ",np.multiply(matrix1,matrix2))

Element Wise subtraction:  [[14  3]
 [ 4 32]]


In [7]:
print("Element Wise subtraction: ",np.divide(matrix1,matrix2))

Element Wise subtraction:  [[3.5 3. ]
 [4.  2. ]]


In [8]:
print("Matrix Multiplication: ",matrix1.dot(matrix2))

Matrix Multiplication:  [[17 19]
 [16 36]]


In [9]:
print("Matrix Multiplication: ",np.dot(matrix1,matrix2))

Matrix Multiplication:  [[17 19]
 [16 36]]


In [10]:
print("Square Root: ",np.sqrt(matrix1))

Square Root:  [[2.64575131 1.73205081]
 [2.         2.82842712]]


In [11]:
print("Summation of all elements in array: ",np.sum(matrix1))

Summation of all elements in array:  22


In [13]:
print("Column wise Summation:",np.sum(matrix1,axis=0))

Column wise Summation: [11 11]


In [14]:
print("Row wise wise Summation:",np.sum(matrix1,axis=1))

Column wise Summation: [10 12]


The matlib package in NumPy is a module that provides functions for creating and manipulating matrices. It primarily offers functions for creating matrices with specific properties, such as identity matrices, zero matrices, and ones matrices. It's a part of NumPy's submodule numpy.matlib.

# empty() function

In [2]:
import numpy as np
import numpy.matlib

mat = np.matlib.empty((2,3))
print(mat)

[[ 7.68983922e-271 -5.26772531e+127  3.94814797e+180]
 [ 1.13477778e+118  2.77734204e+180  1.76525020e+267]]


In [3]:
mat1 = np.matlib.empty((3,2))
print(mat1)

[[7.68983922e-271 5.26772531e+127]
 [3.94814797e+180 1.13477778e+118]
 [2.77734204e+180 1.76525020e+267]]


# zeros() function

In [5]:
mat2 = np.matlib.zeros((3,3))
mat2

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

# ones() function

In [6]:
mat3 = np.matlib.ones((3,3))
mat3

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# eye() function


In [9]:
mat4 = np.matlib.eye(3,3)
mat4

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
mat4 = np.matlib.eye(6,6,k=1)
mat4

matrix([[0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])

In [13]:
mat5 = np.matlib.eye(6,6,k=-1)
mat5

matrix([[0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [15]:
mat6 = np.matlib.identity(5)
mat6

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Vector Multiplication

Scalar Product
Dot Product
Cross Product

Scalar Multiplication:
Scalar multiplication can be represented by multiplying a scalar quantity by all the elements in the vector matrix.

In [17]:
scalar = 5
matrix = np.array([[1,1],[2,2]])
pro = scalar * matrix
print(pro)

[[ 5  5]
 [10 10]]


In [19]:
mat1 = np.array([1,2])
mat2 = np.array([2,1])
print(np.dot(mat1,mat2))

4


In [23]:
mat1 = np.array([1,2])
mat2 = np.array([2,1])
print(np.cross(mat1,mat2))

-3


In [25]:
mat1 = np.array([1,2])
mat2 = np.array([2,1])
print(mat1  @mat2)
# same as dot product

4


# Numpy np.eigvals() method

With the help of np.eigvals() method, we can get the eigen values of a matrix by using np.eigvals() method.

In [33]:
from numpy import linalg
eigen_values=np.linalg.eigvals([[1,2],[2,1]])
eigen_values

array([ 3., -1.])

# Calculate the determinant of a matrix using NumPy

In [39]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
determinent =np.linalg.det(matrix)
print(int(determinent))

0


In [36]:
matrix = np.array([[50, 29], [30, 44]])
determinent =np.linalg.det(matrix)
print(int(determinent))

1330


# NumPy Matrix transpose()

In [43]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

mat2= np.arange(30,39).reshape(3,3)
mat2

In [56]:
new_mat = mat2.transpose()
new_mat

array([[30, 33, 36],
       [31, 34, 37],
       [32, 35, 38]])

# Numpy matrix.var()

With the help of Numpy matrix.var() method, we can find the variance of a matrix by using the matrix.var() method.

In [57]:

# make matrix with numpy 
gmat= np.matrix('[4, 1; 12, 3]')
# applying matrix.var() method 
gmat = gmat.var() 

print(gmat) 


17.5


# inverse of a matrix using NumPy

In [66]:
a1 = np.array([[4,3],[8,3]])
a2= np.arange(80,89).reshape(3,3)
a2 =a2.T

In [67]:
inverse_matrix1 = np.linalg.inv(a1)
inverse_matrix1

array([[-0.25      ,  0.25      ],
       [ 0.66666667, -0.33333333]])

In [71]:
inverse_matrix2 = np.linalg.inv(a2)
inverse_matrix2

array([[-3.51843721e+13,  7.03687442e+13, -3.51843721e+13],
       [ 7.03687442e+13, -1.40737488e+14,  7.03687442e+13],
       [-3.51843721e+13,  7.03687442e+13, -3.51843721e+13]])