# NumPy Copy and View of Array

The main difference between copy and view is that the copy is the new array whereas the view is the view of the original array. In other words, it can be said that the copy is physically stored at another location and the view has the same memory location as the original array

Example: Making a view and changing the original array

In [2]:
import numpy as np

In [8]:
original_array = np.array([1,2,3,4])
original_array

array([1, 2, 3, 4])

In [10]:
v = original_array.view()
v

array([1, 2, 3, 4])

In [11]:
print(id(original_array))
print(id(v))
# both ori and v have different id 

2333162339664
2333144575952


In [12]:
original_array[0]=122
print(original_array)
print(v)
# changing original array 
# this will effect view

[122   2   3   4]
[122   2   3   4]


Copy of Array in NumPy
The copy is completely a new array and the copy owns the data. 

In [14]:
cop = np.copy(original_array)
cop

array([122,   2,   3,   4])

In [16]:
print(id(cop))
print(id(original_array))

2333157371280
2333162339664


In [19]:
original_array[3] = 0
print(original_array)
print(cop)
# changing original array 
# this will not effect copy

[122   2   3   0]
[122   2   3   4]


# How to Copy NumPy array into another array?

In [22]:
ori = np.array([[1,2,3],
              [4,5,6]])
ori

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
copy = np.copy(ori)
copy

array([[1, 2, 3],
       [4, 5, 6]])

# Appending values at the end of an NumPy array

For this task, we can use numpy.append() and numpy.concatenate(). This function can help us to append a single value as well as multiple values at the end of the array.

Appending a Single Value to a 1D Array

In [28]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [29]:
a1 = np.append(a1,[7])
a1

array([1, 2, 3, 4, 7])

Appending Another Array at the End of a 1D Array

In [31]:
a2 = np.array([8,9,10,100])
a3 = np.append(a1,a2)
a3

array([  1,   2,   3,   4,   7,   8,   9,  10, 100])

Appending Values at the End Using Concatenation


In [32]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2 = np.array([[7,8,9]])
combined = np.concatenate((arr1,arr2),axis = 0)
print(combined)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
array = np.arange(1,13,1).reshape(2,6)
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [59]:
#Column
col = np.arange(13,19).reshape(1,6)
print(col.shape)
col_arr = np.append(array,col,axis=0)
print(col_arr)


(1, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [61]:
#Row-Wise
row =np.array([1,11]).reshape(2,1)
row_arr = np.append(array,row,axis = 1)
row_arr

array([[ 1,  2,  3,  4,  5,  6,  1],
       [ 7,  8,  9, 10, 11, 12, 11]])

# How to swap columns of a given NumPy array?

In [65]:
my_array = np.arange(1,13).reshape(4,3)
my_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
#Column swapping
my_array[:,[2,0]] = my_array[:,[0,2]]
my_array

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [67]:
my_array[:,[1,0]]=my_array[:,[0,1]]
my_array

array([[ 2,  3,  1],
       [ 5,  6,  4],
       [ 8,  9,  7],
       [11, 12, 10]])

In [70]:
my_array[[3,0],:]=my_array[[0,3],:]
my_array

array([[11, 12, 10],
       [ 5,  6,  4],
       [ 8,  9,  7],
       [ 2,  3,  1]])

# Insert a new axis within a NumPy array

1D array will become 2D array
2D array will become 3D array
3D array will become 4D array
4D array will become 5D array

Using numpy.expand_dims()

In [71]:
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=1).shape
print(y)


(3, 1, 4)


# numpy.hstack() in Python

numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [76]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
new_array = np.hstack((arr1,arr2))
new_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
arr1 = np.array([[1,2,3,4],
               [5,6,7,8]])
arr2 = np.array([[9,10,11,12],
               [13,14,15,16]])
new_array = np.hstack((arr1,arr2))
new_array

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

# numpy.vstack() in python

In [82]:
arr1 = np.array([[1,2,3,4],
               [5,6,7,8]])
arr2 = np.array([[9,10,11,12],
               [13,14,15,16]])
new_array = np.vstack((arr1,arr2))
new_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Joining NumPy Array

In [85]:
array_1 = np.array([[1,2,3],[7,8,9]])
array_2 = np.array([[4,5,6],[10,11,12]])
new_array = np.concatenate((array_1,array_2),axis =0)
new_array

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [86]:
array_1 = np.array([[1,2,3],[7,8,9]])
array_2 = np.array([[4,5,6],[10,11,12]])
new_array = np.concatenate((array_1,array_2),axis =1)
new_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Method 2: Using numpy.stack()

The stack() function of NumPy joins two or more arrays along a new axis.

In [89]:
array_1 = np.array([[1,2,3],[7,8,9]])
array_2 = np.array([[4,5,6],[10,11,12]])
new_array = np.stack((array_1,array_2),axis =1)
new_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
array_1 = np.array([[1,2,3],[7,8,9]])
array_2 = np.array([[4,5,6],[10,11,12]])
new_array = np.stack((array_1,array_2),axis =0)
new_array

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

 Numpy dstack() method
With the help of numpy.dstack() method, we can get the combined array index by index and store like a stack by using numpy.dstack() method.

In [91]:
array_1 = np.array([[1,2,3],[7,8,9]])
array_2 = np.array([[4,5,6],[10,11,12]])
new_array = np.dstack((array_1,array_2))
new_array

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

# NumPy Splitting Array

The split(), hsplit(), vsplit(), and dsplit() functions are important tools for dividing arrays along various axes and dimensions. 

In [92]:
array = np.arange(1,7)
array

array([1, 2, 3, 4, 5, 6])

In [95]:
arr = np.array_split(array,3)
arr

[array([1, 2]), array([3, 4]), array([5, 6])]

# Splitting NumPy Arrays in Python

1. Splitting Arrays Into Equal Parts using numpy.split()

In [96]:
arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [98]:
array = np.array([1,2,3,4,5,6])
np.split(array,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [99]:
np.split(array,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

2. Unequal Splitting of Arrays using numpy.array_split()

In [101]:
array = np.arange(14)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [102]:
np.array_split(array,4)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10]),
 array([11, 12, 13])]

3. Splitting NumPy 2D Arrays

In [106]:
array = np.arange(1,13).reshape(4,3)
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.split(array,2,axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [110]:
np.array_split(array,2,axis=1)

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

4. Vertical Splitting of Arrays using numpy.vsplit(). It split first dimension

In [133]:
array = np.arange(1,13).reshape(4,3)
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [134]:
array.shape

(4, 3)

In [135]:
np.vsplit(array,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [136]:
array = np.arange(1,13).reshape(4,3)
array


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [137]:
row = np.array([13,14,15,16]).reshape(4,1)
row.shape


(4, 1)

In [138]:
new_array = np.append(array,row,axis = 1)
print(new_array)
print(new_array.shape)

[[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]
 [10 11 12 16]]
(4, 4)


5. Horizontal Splitting of Arrays using numpy.hsplit() . ->it split second dimension

In [139]:
np.hsplit(new_array,2)

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3, 13],
        [ 6, 14],
        [ 9, 15],
        [12, 16]])]

How to compare two NumPy arrays?

In [140]:
import numpy as np


a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a: ", a)
print("Array b: ", b)

print("a > b")
print(np.greater(a, b))

print("a >= b")
print(np.greater_equal(a, b))

print("a < b")
print(np.less(a, b))

print("a <= b")
print(np.less_equal(a, b))


Array a:  [101  99  87]
Array b:  [897  97 111]
a > b
[False  True False]
a >= b
[False  True False]
a < b
[ True False  True]
a <= b
[ True False  True]


# Find the union of two NumPy arrays

To find union of two 1-dimensional arrays we can use function numpy.union1d() of Python Numpy library. It returns unique, sorted array with values that are in either of the two input arrays.

In [142]:
x = np.arange(1,4)
y = np.arange(4,8)
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7])

# Numpy np.unique() method

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [149]:
z = np.array([1,2,3,4,1,6,2,6])
z

array([1, 2, 3, 4, 1, 6, 2, 6])

In [150]:
np.unique(z)

array([1, 2, 3, 4, 6])