In [1]:
import numpy as np

# Random sampling in numpy | ranf() function

numpy.random.ranf() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0)

In [4]:
val1d = np.random.ranf()
val1d

0.7939913559367309

In [6]:
val2d = np.random.ranf(size=(2,1))
val2d

array([[0.44705258],
       [0.81780789]])

In [8]:
val3d = np.random.ranf(size= (3,3,3))
val3d

array([[[0.506964  , 0.39135148, 0.89845221],
        [0.57982745, 0.35263262, 0.89468556],
        [0.94552687, 0.77706062, 0.76983771]],

       [[0.98984597, 0.7455334 , 0.12389561],
        [0.75541252, 0.04759615, 0.45532868],
        [0.19589985, 0.33165031, 0.162321  ]],

       [[0.69192769, 0.88422318, 0.83698842],
        [0.09915366, 0.88271049, 0.94031144],
        [0.35058488, 0.00828266, 0.50672154]]])

# Random sampling in numpy | random() function

numpy.random.random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

In [10]:
val1d=np.random.random(size=4)
val1d

array([0.54523511, 0.01960751, 0.10155192, 0.9250271 ])

In [12]:
val2d=np.random.random(size = (2,1))
val2d

array([[0.73832846],
       [0.16508353]])

In [13]:
val3d = np.random.random(size = (4,3))
val3d

array([[0.36518132, 0.21414479, 0.34880133],
       [0.79707109, 0.02219764, 0.17076723],
       [0.23078627, 0.5752586 , 0.11129445],
       [0.8673182 , 0.24433657, 0.71711439]])

# Random sampling in numpy | random_sample() function

numpy.random.random_sample() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

In [16]:
val = np.random.random_sample(size =5)
val

array([0.90382042, 0.78710671, 0.1344146 , 0.80488058, 0.04085228])

# Random sampling in numpy | randint() function

numpy.random.randint() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).

In [24]:
np.random.randint(low=0,high=100,size= 5)

array([65, 63, 19, 12, 25])

In [25]:
np.random.randint(low = 0, high = 100,size = (5,2))

array([[86, 57],
       [90, 44],
       [21, 20],
       [88, 52],
       [80, 45]])

In [26]:
np.random.randint(low = 0, high = 100,size = (5,2,2))

array([[[61, 11],
        [56, 87]],

       [[43, 53],
        [89, 37]],

       [[25, 12],
        [47, 14]],

       [[46, 86],
        [62, 34]],

       [[94, 21],
        [85, 45]]])

# numpy.random.choice() in Python

With the help of choice() method, we can get the random samples of one dimensional array and return the random samples of numpy array.

In [30]:
np.random.choice((1,2,3,4,5))

5

In [32]:
li = [10,20,30,40]
np.random.choice(li)

10

# numpy.random.shuffle() in python

In [37]:
x = np.arange(1,100,5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [43]:
np.random.shuffle(x)
x

array([26,  1, 21, 66, 61,  6, 81, 36, 96, 91, 86, 46, 31, 16, 11, 71, 56,
       41, 76, 51])