In [2]:
import numpy as np
import math

# Numpy | Mathematical Function

# Trigonometric Functions 

In [5]:
values = [0, math.pi/4,math.pi/2,1]
sin_values = np.sin(values)
print(sin_values)

[0.         0.70710678 1.         0.84147098]


In [6]:
sin_values = np.sin(values)
print(sin_values)

[0.         0.70710678 1.         0.84147098]


In [7]:
cos_values = np.cos(values)
print(cos_values)

[1.00000000e+00 7.07106781e-01 6.12323400e-17 5.40302306e-01]


In [8]:
tan_values = np.tan(values)
print(tan_values)

[0.00000000e+00 1.00000000e+00 1.63312394e+16 1.55740772e+00]


In [9]:
sin_hyperbolic = np.sinh(values)
print(sin_hyperbolic)

[0.         0.86867096 2.3012989  1.17520119]


degrees()	Convert angles from radians to degrees.
rad2deg()	Convert angles from radians to degrees.
deg2rad	Convert angles from degrees to radians.
radians()	Convert angles from degrees to radians.

# Functions for Rounding

In [12]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
new_Arr = np.around(arr)
new_Arr

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [16]:
new_Arr = np.around(arr,decimals= 3)
new_Arr

array([0.   , 0.111, 0.222, 0.333, 0.444, 0.556, 0.667, 0.778, 0.889,
       1.   ])

rint()	Round to nearest integer towards zero.
fix()	Round to nearest integer towards zero.
floor()	Return the floor of the input, element-wise.
ceil()	Return the ceiling of the input, element-wise.
trunc()	Return the truncated value of the input, element-wise.

# Exponents and logarithms Functions 

numpy.exp(array, out = None, where = True, casting = ‘same_kind’, order = ‘K’, dtype = None) : This mathematical function helps user to calculate exponential of all the elements in the input array.

In [17]:
np.exp(new_Arr)

array([1.        , 1.11739491, 1.24857138, 1.3951473 , 1.55893049,
       1.7436838 , 1.94838339, 2.17711368, 2.43269574, 2.71828183])

In [18]:
np.log(new_Arr)

C:\Users\rahul\AppData\Local\Temp\ipykernel_18180\1778330005.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(new_Arr)


array([       -inf, -2.19822508, -1.5050779 , -1.09961279, -0.81193072,
       -0.58698698, -0.40496523, -0.25102875, -0.11765804,  0.        ])

log10()	Return the base 10 logarithm of the input array, element-wise.
log2()	Base-2 logarithm of x.
log1p()	Return the natural logarithm of one plus the input array, element-wise.

# Arithmetic Functions 

numpy.reciprocal(x, /, out=None, *, where=True) : This mathematical function is used to calculate reciprocal of all the elements in the input array.

In [21]:
np.reciprocal(2.0)

0.5

# Numpy | String Operations

In [23]:
np.char.lower(['RAHUL','virat'])

array(['rahul', 'virat'], dtype='<U5')

In [24]:
np.char.split(["Orewa Namikazae Minato"])


array([list(['Orewa', 'Namikazae', 'Minato'])], dtype=object)

In [25]:
np.char.split(['Uzumaki Naruto','Uzumaki Buroto'],sep=',')

array([list(['Uzumaki Naruto']), list(['Uzumaki Buroto'])], dtype=object)

In [29]:
print(np.char.isnumeric('12geeks'))

False


In [31]:
a=np.char.equal('geeks','for')
a

array(False)