In [1]:
import numpy as np

Reshaping numpy array simply means changing the shape of the given array, shape basically tells the number of elements and dimension of array, by reshaping an array we can add or remove dimensions or change number of elements in each dimension.

# Reshaping : 1-D to 2D 

In [6]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Reshaping : 1-D to 3-D

In [14]:
arr = np.arange(1,21).reshape(2,2,5)
arr
#2*2*5=20 = number of elements

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [24]:
arr1 = np.arange(1,51).reshape(2,5,5)
arr1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

# Reshaping N-D to 1-D array

In [18]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
arr1 = np.arange(1,51).reshape(2,5,5)
arr1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [35]:
arr1.reshape(2,25,-1)#3d to 2D

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]],

       [[26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49],
        [50]]])

In [36]:
arr1.reshape(-1)#2D-1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Numpy matrix.resize()

With the help of Numpy matrix.resize() method, we are able to resize the shape of the given matrix. Remember all elements should be covered after resizing the given matrix.

In [42]:
# make matrix with numpy 
my_matrix = np.matrix('[1,2,3];[4,5,6]')

In [44]:
my_matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [46]:
my_matrix.resize((3,2))
my_matrix

matrix([[1, 2],
        [3, 4],
        [5, 6]])

# Numpy matrix.reshape()

In [47]:
mat = np.matrix('[1,2,3,4,5];[6,7,8,9,10]')
mat

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [50]:
mat.reshape((5,2))

matrix([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

# NumPy Array Shape

In [51]:
mat.shape

(2, 5)

In [53]:
my_matrix.shape

(3, 2)

In [54]:
arr1.shape

(2, 5, 5)

# Flatten a Matrix 

In [55]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Numpy matrix.squeeze()

In [56]:
mat = np.matrix('[1,2,3];[4,5,6]')
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [57]:
mat.squeeze()

matrix([[1, 2, 3],
        [4, 5, 6]])