In [2]:
import numpy as np

# Searching in a NumPy array

1. numpy.where:() It returns the indices of elements in an input array where the given condition is satisfied.

In [5]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45]) 
i = np.where(arr == 91)
i

(array([6], dtype=int64),)

# NumPy Array Sorting | How to sort NumPy Array

In [6]:
a = np.array([12, 15, 10, 1]) 
print("Array before sorting",a) 
a.sort() 
print("Array after sorting",a) 


Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]


# Using argsort()

It returns an array of indices that would sort the original array in ascending order.

In [7]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
np.argsort(a)

array([2, 1, 5, 4, 6, 3, 0], dtype=int64)

# Numpy | Sorting, Searching and Counting

numpy.sort() : This function returns a sorted copy of an array.

In [8]:
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1) 

Along first axis : 
 [[10  1]
 [12 15]]


# numpy.nanargmax() : This function returns indices of the max element of the array in a particular axis ignoring NaNs.

In [13]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.nanargmax(array)
#returns the indices

9

numpy.argmin() : This function returns the indices of the minimum values along an axis.

In [15]:
np.argmin(array)

0

numpy.count_nonzero() : Counts the number of non-zero values in the array .

In [16]:
np.count_nonzero(array)

10

numpy.count_nonzero() : Counts the number of non-zero values in the array .

With the help of matrix.sort() method, we are able to sort the values in a matrix by using the same method.

In [22]:
mat = np.matrix('[24,15,5];[61,27,83]')
mat

matrix([[24, 15,  5],
        [61, 27, 83]])

In [23]:
mat.sort()

In [24]:
print(mat)

[[ 5 15 24]
 [27 61 83]]


# Python | Numpy matrix.argsort()

With the help of Numpy matrix.argmax() method, we are able to find the sort the elements in the given matrix having one or more dimension and it would return the index value of sorted elements.

In [26]:
# make a matrix with numpy 
gfg = np.matrix('[1, -2, 3, -4]') 
           
# applying matrix.argsort() method 
geeks = gfg.argsort() 
geeks

matrix([[3, 1, 0, 2]], dtype=int64)

# NumPy ufuncs | Universal functions