In [1]:
import numpy as np

In [2]:
angles = np.array([0, 30, 45, 60, 90, 180])

In [3]:
np.sin(angles)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
       -0.80115264])

In [4]:
np.cos(angles)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
       -0.59846007])

In [5]:
np.tan(angles)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        1.33869021])

In [6]:
np.sinh(angles)

array([0.00000000e+00, 5.34323729e+12, 1.74671355e+19, 5.71003695e+25,
       6.10201647e+38, 7.44692100e+77])

In [7]:
np.deg2rad(angles)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [10]:
b = 3
h=4
np.hypot(b,h)

5.0

In [11]:
# construct a weight array 
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45]) 

# minimum and maximum 
print('Minimum and maximum weight of the students: ') 
print(np.amin(weight), np.amax(weight)) 

# range of weight i.e. max weight-min weight 
print('Range of the weight of the students: ') 
print(np.ptp(weight)) 

# percentile 
print('Weight below which 70 % student fall: ') 
print(np.percentile(weight, 70)) 

# mean 
print('Mean weight of the students: ') 
print(np.mean(weight)) 

# median 
print('Median weight of the students: ') 
print(np.median(weight)) 

# standard deviation 
print('Standard deviation of weight of the students: ') 
print(np.std(weight)) 

# variance 
print('Variance of weight of the students: ') 
print(np.var(weight)) 

# average 
print('Average weight of the students: ') 
print(np.average(weight)) 


Minimum and maximum weight of the students: 
45.0 73.25
Range of the weight of the students: 
28.25
Weight below which 70 % student fall: 
55.317
Mean weight of the students: 
54.3225
Median weight of the students: 
51.6
Standard deviation of weight of the students: 
8.052773978574091
Variance of weight of the students: 
64.84716875
Average weight of the students: 
54.3225
