In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
# creating an array using np.full  
# 255 is code for white color 
array_created = np.full((500, 500, 3), 
                        255, dtype = np.uint8) 
  
# displaying the image 
cv2.imshow("image", array_created)

In [4]:
# Python program to convert 
# numpy array to image 

# import required libraries 
import numpy as np 
from PIL import Image as im 

# define a main function 
def main(): 

    # create a numpy array from scratch
    # using arange function. 
    # 1024x720 = 737280 is the amount 
        # of pixels. 
    # np.uint8 is a data type containing 
    # numbers ranging from 0 to 255 
    # and no non-negative integers 
    array = np.arange(0, 737280, 1, np.uint8) 

    # check type of array 
    print(type(array)) 

    # our array will be of width 
    # 737280 pixels That means it 
    # will be a long dark line 
    print(array.shape) 

    # Reshape the array into a 
    # familiar resoluition 
    array = np.reshape(array, (1024, 720)) 

    # show the shape of the array 
    print(array.shape) 

    # show the array 
    print(array) 

    # creating image object of 
    # above array 
    data = im.fromarray(array) 

    # saving the final output 
    # as a PNG file 
    data.save('gfg_dummy_pic.png') 

# driver code 
if __name__ == "__main__": 

# function call 
  main() 


<class 'numpy.ndarray'>
(737280,)
(1024, 720)
[[  0   1   2 ... 205 206 207]
 [208 209 210 ... 157 158 159]
 [160 161 162 ... 109 110 111]
 ...
 [144 145 146 ...  93  94  95]
 [ 96  97  98 ...  45  46  47]
 [ 48  49  50 ... 253 254 255]]
